### ISSUE TITLE
anime.synopsis returns 'None'

### ISSUE THREAD

**Issue by binsento42** [darenliang/mal-api#7]
I've been messing around with this api and found the anime.synopsis returns 'None' (not <None>).
The synopsis from the AnimeSearch does return a synopsis, be it an abbreviated one. 

In my personal scraper I also used itemprop description for the synopsis and it also broke down recently, so there has probably been some changes to the MAL page layout. I haven't been able to figure out what though, it looks as if the page source still uses description for div property so it's puzzling.

**Comment by darenliang** [comment]
Could you provide an example?

**Comment by darenliang** [comment]
Commit a987fc2 should fix the 'None' synopses.

The newest package version is v0.3.1.

**Comment by darenliang** [comment]
What I find very bizarre is that parsing the synopses on Mangas work.

The culprit seems to be that the Anime synopsis element header is a `div` rather than `h2`. No idea why they have this inconsistency.

Manga pages: `<h2 style="margin-top: 15px;">`
Anime pages: `<div style="margin-top: 15px;">`

You see for yourself by inspecting the "Background" text on an Anime/Manga page.

**Comment by binsento42** [comment]
It is fixed indeed; I rebuilt the docker container and to test it and the synopsis works now. MAL regularly changes the page code so I have been forced to fix my scraper several times the past few years. I'd noticed the div but couldn't track down why it wouldn't work anymore. I'll have a look at it again. Thanks for the quick fix.
